const path = require('path');
const initializeSubs = require('./src/initialize');
const subtitles = require('./src/subtitles');
const generateAudio = require('./src/audio').generateAudio;
const updateAudio = require('./src/audio').updateAudio;
const createAnkiDb = require('./src/database');
const apkgCreater = require('./src/archiver');
const utils = require('./src/utils');

exports.initializeSubs = initializeSubs;
exports.transformSubs = subtitles.subsTransform;
exports.generateAudio = generateAudio;
exports.updateAudio = updateAudio;
exports.extractSubs = subtitles.extract;
exports.listEmbeddedSubs = subtitles.listEmbedded;
exports.getAudioDir = () => path.resolve('pkg');
exports.createAnkiDb = createAnkiDb;
exports.createApkg = apkgCreater;
exports.rmFile = utils.rmFile;
exports.rmFiles = utils.rmFiles;
exports.updateFileVersionHash = utils.updateFileVersionHash;
exports.quickName = utils.quickName;
exports.combineSubtitles = utils.combineSubtitles;
